name: Compress Images
on:
  pull_request:
    # Run Image Actions when JPG, JPEG, PNG or WebP files are added or changed.
    # See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths for reference.
    paths:
      - 'img/**'
      - 'album/**'
      - 'emoji/**'
    paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
      - 'readme.md'
      - 'deploy.sh'
  push:
    branches:
      - master
    paths:
      - 'img/**'
      - 'album/**'
      - 'emoji/**'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: Compress Images
        uses: calibreapp/image-actions@1.1.0
        with:
          githubToken: ${{ secrets.MG }}
          jpegQuality: "80"
          pngQuality: "100"
          webpQuality: "80"
          ignorePaths: "node_modules/**"
